sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: lY8xIp2/AILOhNMlKgcRzfhdHywNGabhe/Rxwwff7UtOuFyfFsscC1g7crImTi29JyJE1WoAwcmo/lm346O/v+pyg7LXpS6MUta2Zv49ZfTrD0W/o27xOj+gJ2JHTkPqmfhtUkotOE2eqUYoZk7VRZGnFif9sODNy8lFscWiRUTKTDgArlhJdBIZKaEylw3SGN4/Hov5GyyJGkqLXlozqddnZCYR6WkWHQhiEIeBF9zw8AC0Kakt6c+HGBLH/ny0WLwILFviZti8J75jIpY0Gkt4tOpP648vQRVn+A54USacl4MY2h3vxCDAb8dAtoevCQL6tiCLBIlu81PfjwfAVnW2AeiJzAZRk0JlZZWcI7CyVNyZYxkptgfqVieXMAQ/Xu8sH8oCS2odGrjdog/cpeKm20h2ZZrBZBE/ds9aXNXr5aJMbvr503m1zf15ZbXBzozBTCorcDm+ObmS2+ZOvNykpmJZ6DFsPfyJeLcmRZKpCdLjYVF5/rjyb7QiBUpIvvlx+t0YckhCzCi8NiXDwI4PA0s10wvXqBJYQAChRNpGkpnIZY5rP0VjCFmHorc9JihNZpsml1AbOFdZCrDnhVGytkxGOSwe/YxgXTwbszIT5kOqlTCtDSfNA8UU11XiENeAt81zoCh4ntg4d2MpbPH7w5vdkSj3NhanHENj0Ec=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Songs-of-Action_4295
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy